/* Generated by Amaranth Yosys 0.50 (PyPI ver 0.50.0.0.post121, git sha1 b5170e139) */

(* top =  1  *)
(* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:22" *)
(* generator = "Amaranth" *)
module top(current_floor_sensor, door_sensor, emergency, overload, clk, rst, motor_up, motor_down, door_open, door_close, current_floor, floor_request);
  reg \$auto$verilog_backend.cc:2355:dump_module$1  = 0;
  wire \$1 ;
  wire \$10 ;
  wire \$11 ;
  wire \$12 ;
  wire \$13 ;
  wire \$14 ;
  wire \$15 ;
  wire \$16 ;
  wire \$17 ;
  wire \$18 ;
  wire \$19 ;
  wire \$2 ;
  wire \$20 ;
  wire \$21 ;
  wire \$22 ;
  wire \$23 ;
  wire \$24 ;
  wire \$25 ;
  wire \$26 ;
  wire \$27 ;
  wire [3:0] \$28 ;
  wire [3:0] \$29 ;
  wire [2:0] \$3 ;
  wire [3:0] \$30 ;
  wire \$31 ;
  wire \$32 ;
  wire \$33 ;
  wire [3:0] \$34 ;
  wire [3:0] \$35 ;
  wire [3:0] \$36 ;
  wire [24:0] \$37 ;
  wire \$38 ;
  wire \$39 ;
  wire [3:0] \$4 ;
  wire \$40 ;
  wire \$41 ;
  wire \$42 ;
  wire \$43 ;
  wire \$44 ;
  wire \$45 ;
  wire \$46 ;
  wire \$47 ;
  reg [1:0] \$48 ;
  reg [3:0] \$49 ;
  wire \$5 ;
  reg [2:0] \$50 ;
  reg [1:0] \$51 ;
  reg [23:0] \$52 ;
  wire [3:0] \$6 ;
  wire [3:0] \$7 ;
  wire [3:0] \$8 ;
  wire \$9 ;
  (* src = "/home/fabio_testino/elevator-amaranth/venv/lib/python3.12/site-packages/amaranth/hdl/_ir.py:283" *)
  input clk;
  wire clk;
  (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:26" *)
  output [1:0] current_floor;
  reg [1:0] current_floor = 2'h0;
  (* init = 2'h0 *)
  (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:26" *)
  wire [1:0] \current_floor$12 ;
  (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:9" *)
  input [3:0] current_floor_sensor;
  wire [3:0] current_floor_sensor;
  (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:18" *)
  reg [2:0] current_state;
  (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:17" *)
  output door_close;
  wire door_close;
  (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:16" *)
  output door_open;
  wire door_open;
  (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:10" *)
  input door_sensor;
  wire door_sensor;
  (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:28" *)
  reg [23:0] door_timer = 24'h000000;
  (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:11" *)
  input emergency;
  wire emergency;
  (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:8" *)
  input [3:0] floor_request;
  wire [3:0] floor_request;
  (* src = "/usr/lib/python3.12/contextlib.py:144" *)
  reg [2:0] fsm_state = 3'h0;
  (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:15" *)
  output motor_down;
  wire motor_down;
  (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:14" *)
  output motor_up;
  wire motor_up;
  (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:12" *)
  input overload;
  wire overload;
  (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:25" *)
  reg [3:0] request_queue = 4'h0;
  (* src = "/home/fabio_testino/elevator-amaranth/venv/lib/python3.12/site-packages/amaranth/hdl/_ir.py:283" *)
  input rst;
  wire rst;
  (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:27" *)
  reg [1:0] target_floor = 2'h0;
  assign motor_up = fsm_state == (* src = "/home/fabio_testino/elevator-amaranth/venv/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) 2'h3;
  assign motor_down = fsm_state == (* src = "/home/fabio_testino/elevator-amaranth/venv/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) 3'h4;
  assign \$47  = fsm_state == (* src = "/home/fabio_testino/elevator-amaranth/venv/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) 3'h5;
  assign door_close = fsm_state == (* src = "/home/fabio_testino/elevator-amaranth/venv/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) 3'h6;
  (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:26" *)
  always @(posedge clk)
    current_floor <= \$48 ;
  (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:25" *)
  always @(posedge clk)
    request_queue <= \$49 ;
  (* src = "/usr/lib/python3.12/contextlib.py:144" *)
  always @(posedge clk)
    fsm_state <= \$50 ;
  (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:27" *)
  always @(posedge clk)
    target_floor <= \$51 ;
  (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:28" *)
  always @(posedge clk)
    door_timer <= \$52 ;
  assign \$1  = | (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:50" *) request_queue;
  assign \$2  = request_queue >> current_floor;
  assign \$3  = current_floor + (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:57" *) 1'h1;
  assign \$4  = request_queue >> (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:57" *) \$3 ;
  assign \$5  = | (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:57" *) \$4 ;
  assign \$6  = 1'h1 << (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:54" *) current_floor;
  assign \$7  = ~ (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:54" *) \$6 ;
  assign \$8  = request_queue & (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:54" *) \$7 ;
  assign \$9  = current_floor < (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:59" *) 2'h3;
  assign \$10  = request_queue[3] & (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:59" *) \$9 ;
  assign \$11  = current_floor < (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:59" *) 2'h2;
  assign \$12  = request_queue[2] & (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:59" *) \$11 ;
  assign \$13  = current_floor < (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:59" *) 1'h1;
  assign \$14  = request_queue[1] & (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:59" *) \$13 ;
  assign \$15  = current_floor < (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:59" *) 1'h0;
  assign \$16  = request_queue[0] & (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:59" *) \$15 ;
  assign \$17  = current_floor > (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:64" *) 1'h0;
  assign \$18  = request_queue[0] & (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:64" *) \$17 ;
  assign \$19  = current_floor > (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:64" *) 1'h1;
  assign \$20  = request_queue[1] & (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:64" *) \$19 ;
  assign \$21  = current_floor > (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:64" *) 2'h2;
  assign \$22  = request_queue[2] & (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:64" *) \$21 ;
  assign \$23  = current_floor > (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:64" *) 2'h3;
  assign \$24  = request_queue[3] & (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:64" *) \$23 ;
  assign \$25  = current_floor == (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:74" *) target_floor;
  assign \$26  = request_queue >> current_floor;
  assign \$27  = \$25  | (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:74" *) \$26 ;
  assign \$28  = 1'h1 << (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:77" *) current_floor;
  assign \$29  = ~ (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:77" *) \$28 ;
  assign \$30  = request_queue & (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:77" *) \$29 ;
  assign \$31  = current_floor == (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:86" *) target_floor;
  assign \$32  = request_queue >> current_floor;
  assign \$33  = \$31  | (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:86" *) \$32 ;
  assign \$34  = 1'h1 << (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:89" *) current_floor;
  assign \$35  = ~ (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:89" *) \$34 ;
  assign \$36  = request_queue & (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:89" *) \$35 ;
  assign \$37  = door_timer + (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:103" *) 1'h1;
  assign \$38  = door_timer >= (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:107" *) 6'h32;
  assign \$39  = ~ (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:115" *) door_sensor;
  assign \$40  = ~ (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:120" *) emergency;
  assign \$41  = ~ (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:120" *) door_sensor;
  assign \$42  = \$40  & (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:120" *) \$41 ;
  assign \$43  = \$46  | (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:127" *) \$47 ;
  assign door_open = \$43  | (* src = "/home/fabio_testino/elevator-amaranth/elevator_controller.py:127" *) \$45 ;
  assign \$44  = ! (* src = "/home/fabio_testino/elevator-amaranth/venv/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) fsm_state;
  assign \$45  = fsm_state == (* src = "/home/fabio_testino/elevator-amaranth/venv/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) 1'h1;
  assign \$46  = fsm_state == (* src = "/home/fabio_testino/elevator-amaranth/venv/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) 2'h2;
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$48  = current_floor;
    if (current_floor_sensor[0]) begin
      \$48  = 2'h0;
    end
    if (current_floor_sensor[1]) begin
      \$48  = 2'h1;
    end
    if (current_floor_sensor[2]) begin
      \$48  = 2'h2;
    end
    if (current_floor_sensor[3]) begin
      \$48  = 2'h3;
    end
    if (rst) begin
      \$48  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$49  = request_queue;
    if (floor_request[0]) begin
      \$49 [0] = 1'h1;
    end
    if (floor_request[1]) begin
      \$49 [1] = 1'h1;
    end
    if (floor_request[2]) begin
      \$49 [2] = 1'h1;
    end
    if (floor_request[3]) begin
      \$49 [3] = 1'h1;
    end
    casez (fsm_state)
      3'h0:
          if (emergency) begin
            \$49  = 4'h0;
          end else if (\$1 ) begin
            if (\$2 ) begin
              \$49  = \$8 ;
            end
          end
      3'h3:
          if (emergency) begin
            \$49  = 4'h0;
          end else if (\$27 ) begin
            \$49  = \$30 ;
          end
      3'h4:
          if (emergency) begin
            \$49  = 4'h0;
          end else if (\$33 ) begin
            \$49  = \$36 ;
          end
      3'h2:
          if (emergency) begin
            \$49  = 4'h0;
          end
      3'h5:
          if (emergency) begin
            \$49  = 4'h0;
          end
      3'h6:
          if (emergency) begin
            \$49  = 4'h0;
          end
    endcase
    if (rst) begin
      \$49  = 4'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$50  = fsm_state;
    casez (fsm_state)
      3'h0:
          if (emergency) begin
            \$50  = 3'h1;
          end else if (\$1 ) begin
            (* full_case = 32'd1 *)
            if (\$2 ) begin
              \$50  = 3'h2;
            end else if (\$5 ) begin
              \$50  = 3'h3;
            end else begin
              \$50  = 3'h4;
            end
          end
      3'h3:
          if (emergency) begin
            \$50  = 3'h1;
          end else if (\$27 ) begin
            \$50  = 3'h2;
          end
      3'h4:
          if (emergency) begin
            \$50  = 3'h1;
          end else if (\$33 ) begin
            \$50  = 3'h2;
          end
      3'h2:
          if (emergency) begin
            \$50  = 3'h1;
          end else if (door_sensor) begin
            \$50  = 3'h5;
          end
      3'h5:
          if (emergency) begin
            \$50  = 3'h1;
          end else if (\$38 ) begin
            \$50  = 3'h6;
          end
      3'h6:
          if (emergency) begin
            \$50  = 3'h1;
          end else if (\$39 ) begin
            \$50  = 3'h0;
          end
      3'h1:
          if (\$42 ) begin
            \$50  = 3'h0;
          end
    endcase
    if (rst) begin
      \$50  = 3'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$51  = target_floor;
    casez (fsm_state)
      3'h0:
          if (emergency) begin
          end else if (\$1 ) begin
            (* full_case = 32'd1 *)
            if (\$2 ) begin
              \$51  = current_floor;
            end else if (\$5 ) begin
              if (\$10 ) begin
                \$51  = 2'h3;
              end
              if (\$12 ) begin
                \$51  = 2'h2;
              end
              if (\$14 ) begin
                \$51  = 2'h1;
              end
              if (\$16 ) begin
                \$51  = 2'h0;
              end
            end else begin
              if (\$18 ) begin
                \$51  = 2'h0;
              end
              if (\$20 ) begin
                \$51  = 2'h1;
              end
              if (\$22 ) begin
                \$51  = 2'h2;
              end
              if (\$24 ) begin
                \$51  = 2'h3;
              end
            end
          end
    endcase
    if (rst) begin
      \$51  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$52  = door_timer;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h3:
          /* empty */;
      3'h4:
          /* empty */;
      3'h2:
          if (emergency) begin
          end else if (door_sensor) begin
            \$52  = 24'h000000;
          end
      3'h5:
          \$52  = \$37 [23:0];
    endcase
    if (rst) begin
      \$52  = 24'h000000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    current_state = 3'h0;
    casez (fsm_state)
      3'h0:
          current_state = 3'h0;
      3'h3:
          current_state = 3'h1;
      3'h4:
          current_state = 3'h2;
      3'h2:
          current_state = 3'h3;
      3'h5:
          current_state = 3'h4;
      3'h6:
          current_state = 3'h5;
      3'h1:
          current_state = 3'h6;
    endcase
  end
  assign \current_floor$12  = current_floor;
endmodule
